function on_message(self, message_id, message, sender)
	local size = vmath.vector3(10, 10, 0)
	if message_id == hash('draw_square') and message.data then
		for i = 1, #message.data do
			local c = message.data:sub(i, i)
			if c == '#' then
				local position = vmath.vector3(message.x + (i*10), message.y, 0)
				local boxnode = gui.new_box_node(position, size)
				gui.set_color(boxnode, vmath.vector4(1, 1, 1, 1))
			end
		end
	end
end
